source 'https://github.com/CocoaPods/Specs.git'

target 'ZettaKit', :exclusive => true do
  pod "ZettaKit", :path => "../"
  pod 'SocketRocket', '0.3.1-beta2'
  pod 'SHMKit', '~> 0.1'
end

target 'Tests', :exclusive => true do
  pod "ZettaKit", :path => "../"
  pod 'SocketRocket', '0.3.1-beta2'
  pod 'SHMKit', '~> 0.1'
  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end
